"""Add achievement rewards

Revision ID: d53b6a7294b0
Revises: 
Create Date: 2026-07-11 12:08:38.682030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53b6a7294b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('xp_reward', sa.Integer(), nullable=True))
    op.add_column('achievements', sa.Column('gem_reward', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'gem_reward')
    op.drop_column('achievements', 'xp_reward')
    # ### end Alembic commands ###
